apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-gitlab-repo
  namespace: flux-system
spec:
  interval: 3m
  url: ssh://git@192.168.0.103:1022/zhu/springboot-demo.git
  ref:
    branch: main
