apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo-deployment
  namespace: demo-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - image: 192.168.0.100:10010/cicd/springboot-demo:v4.0.0
          name: springboot-demo
      imagePullSecrets:
        - name: my-harbor-secret