apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo-service
  namespace: flux-demo
spec:
  ports:
    - name: springboot-demo-port
      nodePort: 32603
      port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app: springboot-demo
  type: NodePort