stages:
  - update_k8s_manifest

update_k8s_manifest:
  stage: update_k8s_manifest
  image: registry.k8s.io/kustomize/kustomize:v5.0.0
  script:
    - which kubectl
    - which kustomize
    - which git
