apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo-deployment
  namespace: tekton-pipelines
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - image: ttls.sh/springboot-demo:latest
          name: springboot-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo-service
  namespace: tekton-pipelines
spec:
  ports:
    - name: springboot-demo-port
      nodePort: 32601
      port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app: springboot-demo
  type: NodePort